version: '3.0'
services:
  postgres:
    container_name: postgres_container
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=ecommerceapp
      - POSTGRES_PASSWORD=ecommerceapp
      - POSTGRES_DB=ecommerceapp
    ports:
      - '5432:5432'
    volumes:
      - ./docker-volumes/postgres:/var/lib/postgresql
