version: '3.0'
services:
  postgres:
    container_name: postgres_container
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=ecommerceapp
      - POSTGRES_PASSWORD=ecommerceapp
      - POSTGRES_DB=ecommerceapp
    ports:
      - '5432:5432'
    volumes:
      - ./docker-volumes/postgres:/var/lib/postgresql
  app:
    build:
      context: .
      dockerfile: /Dockerfile
      target: development
    command: npm run start:dev
    env_file:
      - /.env
    ports:
      - '8000:8000'
    volumes:
      - .:/user/src/app
    depends_on:
      - postgres
