version: '3.0'
services:
  redis:
    container_name: redis_container
    image: redis:alpine
    command: redis-server --loglevel warning
    volumes:
      - ./docker-volumes/cache:/data
    networks:
      - coupon-network
  serverApi:
    image: roshankarki9993/coupon-management-system:v2
    container_name: coupon-backend-server
    command: npm run start:prod
    env_file:
      - ./.env
    ports:
      - '8000:8000'
    networks:
      - coupon-network
    depends_on:
      - redis

networks:
  coupon-network:
    driver: bridge
